name: Kotlin CI

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test